#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
if tty -s
then
    tmpfile=
else
    tmpfile=$(mktemp -t ggrep.XXXXXX)
    cat > "$tmpfile"
    exec < "$tmpfile"
fi
xc=0
grep "$@" || xc=$?
[ $xc -lt 2 ] || exit $xc
if [ -n "$tmpfile" ]
then
    exec < "$tmpfile"
fi
exec grep -v "$@"

# vim:ts=4 sts=4 sw=4 et
